name: pylag
channels:
  - nodefaults
  - conda-forge
  - geo-down-under
  - JimClark
dependencies:
  - python=3.9
  - pylag
  - matplotlib
  - cartopy
  - cmocean
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - sphinxcontrib-napoleon
  - jupyter
  - jupyter_client
  - ipykernel
