name: pylag
channels:
  - conda-forge
dependencies:
  - python
  - mpi4py
  - numpy>=2.0
  - scipy>=1.4.1
  - cython>=3.0
  - progressbar
  - natsort
  - netCDF4
  - cftime>=1.1
  - configparser
  - stripy
  - shapely
  - pyproj
  - pytest
